version: '3'

services:
  
  nginx:
    build:
      .
    networks:
      - nginx
    ports:
      - '8080:8080'
      - '4433:4433'
    volumes:
      - ./samples/default:/etc/nginx/sites-available/default
      - ./samples/deafault.conf:/etc/nginx/nginx.conf

networks:
  nginx:
    